In [1]:
class demo:
    def test(self):
        print("test() for the class and method")
        return
obj=demo()
obj.test()

    

test() for the class and method


In [2]:
def test():
    print("test() for function")
    return
test()

test() for function


In [4]:
class demo1:
    def fact(self,n):
        fact=1
        while(n!=0):
            fact=fact*n
            n = n -1
        return fact
    
p1=demo1()
p1.fact(5)
    

120

In [5]:
class demo2:
    def accept(self,p1,p2):
        a=p1
        b=p2
        return
    def display(self):
        print("a= ",a)
        print("b= ",b)
        
c1=demo2()
c1.accept(10,20)
c1.display()
    

NameError: name 'a' is not defined

In [8]:
class demo2():
    def _init_(self,p1,p2):
        self.p1=p1
        self.p2=p2
        
    def add(self,p1,p2):
        return p1+p2
c1=demo2()
print(c1.add(100,200))
        
    

300


In [3]:
class person(object):
    def _int_(self,name):
        self,name = name
        def getname(self):
            return self.name
        def isemployee(self):
            return False
        
        
class employee(person):
    def isemployee(self):
        return True
    
emp=person("anil")
print(emp.getname(),emp.isemployee())
emp1=employee("akhil")
print(emp.getname(),emp.isemployee())

TypeError: person() takes no arguments

In [4]:
lst=[1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [5]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [6]:
a1 = np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
a1 = np.array([1,2,3,4])
a2 = np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 4 5 6]


In [13]:
import numpy as np
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [12]:
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)


(4,)
int64


In [15]:
import numpy as np
a1 = np.random.normal(5,0.5,10)
print(a1)

[4.65345932 4.76646772 5.28364533 5.33569343 4.9474117  5.15577424
 4.60017797 4.68361567 4.81729101 5.26012714]


In [16]:
import numpy as np
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [18]:
import numpy as np

np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]])

In [19]:
import numpy as np
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [20]:
lst=[1.0,2.5,3.6,9.5]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
float64


In [21]:
import numpy as np
A = np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [22]:
import numpy as np
A = np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)


[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [2]:
import numpy as np
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [3]:
import numpy as np
a1=np.array([(1,2,3),(4,5,6)])
print("first row :",a1[0])



first row : [1 2 3]


In [4]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [7]:
import numpy as np
a1 = np.array([(1,2,3),(4,5,6)])
print("second row: ",a1[1])

second row:  [4 5 6]


In [8]:
import numpy as np
a1 = np.array([(1,2,3),(4,5,6)])
print("slicing last column : ",a1[:,2])

slicing last column :  [3 6]


In [9]:
import numpy as np
a1 = np.array([(1,2,3),(4,5,6)])
print("row and column : ",a1[1,:1])

row and column :  [4]


In [10]:
import numpy as np
a1=np.random.normal(5,1,10)
print(a1)
print("min value = ",np.min(a1))
print("max value = ",np.max(a1))
print("mean value = ",np.mean(a1))
print("median value = ",np.median(a1))
      

[6.52368849 5.93844377 3.12476881 4.98009509 5.18717622 4.35768437
 5.17546856 5.45341813 4.96998474 3.78976352]
min value =  3.1247688131025066
max value =  6.523688487778769
mean value =  4.950049169854343
median value =  5.077781823054721


In [11]:
import numpy as np
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)


14

In [12]:
import numpy as np
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)


array([[ 5,  8],
       [13, 20]])

In [14]:
import numpy as np
b1=np.array([(1,5),(6,9)])
b2=np.array([(1,3),(1,6)])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])

In [ ]:
import pandas as pd
dict={"name":[]}